name: Build and Publish ip2cidr to PyPI

on:
  push:
    tags:
      - 'ip2cidr-v*'  # Trigger on version tags for ip2cidr
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  pypi:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ip2cidr
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      working-directory: ./ip2cidr
      run: python -m build

    - name: Publish to PyPI
      working-directory: ./ip2cidr
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*