name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      working-directory: ./azure-pipeline-variable-list
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
        pip install pytest pytest-cov

    - name: Run tests
      working-directory: ./azure-pipeline-variable-list
      run: |
        pytest --cov=src --cov-report=xml
